"""
Certificate Service — Generates high-fidelity, verified skill certificates as PDF.
Uses a landscape orientation with the 2026 SkillMentor AI brand identity.
"""
import io
import logging
from datetime import datetime
from typing import Dict, Any
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.units import mm
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas

from app.core.database import get_supabase
from app.services.notes_service import _resolve_storage_bucket, _build_download_url

logger = logging.getLogger(__name__)

# --- Modern Dark Theme Palette ---
C_BG      = HexColor("#080B14")
C_ACCENT  = HexColor("#4FFFA0")  # SkillMentor Neon Green
C_BLUE    = HexColor("#5B8EFF")
C_TEXT_H  = HexColor("#E8EDF8")
C_MUTED   = HexColor("#6B7A99")
C_BORDER  = HexColor("#1E2A42")


def _adaptive_font_size(text: str, base: int, min_size: int, step_every: int = 8) -> int:
    """Shrink font size for long text to avoid overlapping on certificate."""
    length = len((text or "").strip())
    if length <= step_every:
        return base
    reduction = (length - step_every) // step_every
    return max(min_size, base - reduction)


def _fit_center_text(text: str, max_chars_per_line: int, max_lines: int = 2) -> tuple[str, int, int]:
    """Wrap long text into max two lines and truncate safely with ellipsis if needed.

    Returns: (xml_escaped_text_with_br, line_count, longest_line_len)
    """
    words = (text or "").strip().split()
    if not words:
        return "", 1, 0

    lines: list[str] = []
    current = ""
    for w in words:
        candidate = f"{current} {w}".strip()
        if len(candidate) <= max_chars_per_line:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = w
        if len(lines) >= max_lines:
            break

    if len(lines) < max_lines and current:
        lines.append(current)

    if len(lines) > max_lines:
        lines = lines[:max_lines]

    consumed = " ".join(lines).split()
    if len(consumed) < len(words):
        last = lines[-1]
        lines[-1] = (last[:-1] + "…") if len(last) >= max_chars_per_line else (last + "…")

    safe = "<br/>".join(escape(line) for line in lines)
    longest = max((len(line) for line in lines), default=0)
    return safe, max(1, len(lines)), longest


def _draw_fit_text(
    c: canvas.Canvas,
    text: str,
    font_name: str,
    start_size: int,
    min_size: int,
    max_width: float,
    x: float,
    y: float,
    centered: bool = False,
) -> int:
    """Draw single-line text by shrinking font size until it fits max width."""
    size = start_size
    content = text or ""
    while size > min_size and stringWidth(content, font_name, size) > max_width:
        size -= 1

    c.setFont(font_name, size)
    if centered:
        c.drawCentredString(x, y, content)
    else:
        c.drawString(x, y, content)
    return size

async def generate_skill_certificate(
    user_id: str,
    roadmap_id: str,
    skill: str,
    level: str,
    full_name: str,
) -> Dict[str, Any]:
    """
    Generates a branded, landscape-oriented certificate.
    Persists to Supabase Storage and updates the verification record.
    """
    supabase = get_supabase()

    # 1. Aggregate Final Stats for the "Proof of Skill" section
    progress_res = supabase.table("user_progress").select("xp_points,lessons_completed,quizzes_completed") \
        .eq("user_id", user_id).single().execute()
    
    projects_res = supabase.table("projects").select("id", count="exact") \
        .eq("user_id", user_id).eq("status", "submitted").execute()

    prog = progress_res.data or {}
    xp = prog.get("xp_points", 0)
    lessons = prog.get("lessons_completed", 0)
    quizzes = prog.get("quizzes_completed", 0)
    projects = projects_res.count or 0

    # 2. Check for existing certificate
    existing = supabase.table("certificates").select("id, pdf_url, verify_code") \
        .eq("user_id", user_id).eq("skill", skill).eq("level", level).execute()

    existing_cert = existing.data[0] if existing.data else None

    # 3. Initialize Verification Record (only if missing)
    # Note: verify_code is usually a NanoID or Hash generated by a DB trigger
    if existing_cert:
        cert = {
            "id": existing_cert.get("id"),
            "verify_code": existing_cert.get("verify_code"),
        }
        # Keep metadata fresh for existing records.
        supabase.table("certificates").update({
            "roadmap_id": roadmap_id,
            "full_name": full_name,
            "xp_at_issue": xp,
            "lessons_count": lessons,
            "projects_count": projects,
            "quizzes_count": quizzes,
        }).eq("id", cert["id"]).execute()
    else:
        cert_row = supabase.table("certificates").insert({
            "user_id": user_id,
            "roadmap_id": roadmap_id,
            "skill": skill,
            "level": level,
            "full_name": full_name,
            "xp_at_issue": xp,
            "lessons_count": lessons,
            "projects_count": projects,
            "quizzes_count": quizzes,
        }).execute()

        if not cert_row.data:
            raise RuntimeError("Failed to initialize certificate record.")

        cert = cert_row.data[0]
    verify_code = cert.get("verify_code", cert["id"][:8].upper())
    issued_date = datetime.now().strftime("%B %d, %Y")

    # 4. Build PDF Document (reference-style formal certificate layout)
    buffer = io.BytesIO()
    page_w, page_h = landscape(A4)
    c = canvas.Canvas(buffer, pagesize=(page_w, page_h))

    # Palette tuned for clean, institutional look.
    bg = HexColor("#F6F7F9")
    text_dark = HexColor("#1D2433")
    text_muted = HexColor("#5A6780")
    accent = HexColor("#3F7AE0")
    line = HexColor("#C9CFDA")
    panel = HexColor("#E5E8EE")

    # Background + double border
    c.setFillColor(bg)
    c.rect(0, 0, page_w, page_h, fill=1, stroke=0)
    c.setStrokeColor(line)
    c.setLineWidth(1)
    c.rect(10, 10, page_w - 20, page_h - 20, fill=0, stroke=1)
    c.rect(16, 16, page_w - 32, page_h - 32, fill=0, stroke=1)

    # Right ribbon panel
    panel_x = page_w * 0.70
    panel_w = page_w * 0.16
    panel_top = page_h - 24
    panel_bottom = 100
    c.setFillColor(panel)
    c.setStrokeColor(line)
    c.rect(panel_x, panel_bottom + 24, panel_w, panel_top - panel_bottom - 24, fill=1, stroke=1)
    tip = c.beginPath()
    tip.moveTo(panel_x, panel_bottom + 24)
    tip.lineTo(panel_x + panel_w, panel_bottom + 24)
    tip.lineTo(panel_x + panel_w / 2, panel_bottom - 32)
    tip.close()
    c.drawPath(tip, fill=1, stroke=1)

    # Right panel heading + seal
    c.setFillColor(text_dark)
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(panel_x + panel_w / 2, page_h - 86, "SKILL")
    c.drawCentredString(panel_x + panel_w / 2, page_h - 104, "CERTIFICATE")
    c.setStrokeColor(text_muted)
    c.circle(panel_x + panel_w / 2, page_h * 0.45, 42, fill=0, stroke=1)
    c.circle(panel_x + panel_w / 2, page_h * 0.45, 34, fill=0, stroke=1)
    c.setFillColor(text_dark)
    c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(panel_x + panel_w / 2, page_h * 0.45 - 5, "verified")

    # Left content area
    left_x = 48
    content_w = panel_x - left_x - 28

    c.setFillColor(HexColor("#1FAF62"))
    c.setFont("Helvetica-Bold", 13)
    c.drawString(left_x, page_h - 72, "SKILLMENTOR AI")
    c.setFillColor(text_muted)
    c.setFont("Helvetica", 10)
    c.drawString(left_x, page_h - 90, issued_date)

    c.setFillColor(text_dark)
    c.setFont("Times-Bold", 24)
    c.drawString(left_x, page_h - 132, "Certificate of Completion")

    c.setFillColor(text_muted)
    c.setFont("Times-Roman", 12)
    c.drawString(left_x, page_h - 164, "This is to certify that")

    _draw_fit_text(c, full_name, "Times-Bold", 30, 20, content_w, left_x, page_h - 204)

    c.setFillColor(text_muted)
    c.setFont("Times-Roman", 12)
    c.drawString(left_x, page_h - 228, "has successfully demonstrated mastery in")

    # Multi-line course/skill title
    skill_title = f"{skill} ({level.title()} Level)"
    words = skill_title.split()
    lines = []
    line_buf = ""
    for w in words:
        cand = f"{line_buf} {w}".strip()
        if stringWidth(cand, "Times-Bold", 18) <= content_w:
            line_buf = cand
        else:
            lines.append(line_buf)
            line_buf = w
    if line_buf:
        lines.append(line_buf)
    lines = lines[:2]
    if len(lines) == 2 and len(words) > len((lines[0] + " " + lines[1]).split()):
        lines[1] = (lines[1][:-1] + "…") if len(lines[1]) > 3 else lines[1]

    c.setFillColor(accent)
    c.setFont("Times-Bold", 18)
    y = page_h - 262
    for idx, ln in enumerate(lines):
        c.drawString(left_x, y - idx * 24, ln)

    c.setFillColor(text_muted)
    c.setFont("Helvetica", 11)
    stats_text = f"Achievement: {xp:,} XP • {lessons} lessons • {quizzes} assessments • {projects} projects"
    c.drawString(left_x, page_h - 318, stats_text)

    c.setStrokeColor(line)
    c.setLineWidth(1)
    c.line(left_x, page_h - 348, left_x + content_w, page_h - 348)

    # Signature block
    sig_y = 120
    c.setStrokeColor(line)
    c.line(left_x, sig_y + 22, left_x + 200, sig_y + 22)
    c.setFillColor(text_muted)
    c.setFont("Helvetica", 9)
    c.drawString(left_x, sig_y + 8, "Program Director")
    c.drawString(left_x, sig_y - 6, "SkillMentor AI Academy")

    verify_url = f"skillmentor.ai/verify/{verify_code}"
    c.setFont("Courier", 9)
    c.drawRightString(left_x + content_w, sig_y + 10, f"Verify at: {verify_url}")
    c.drawRightString(left_x + content_w, sig_y - 6, f"Verification code: {verify_code}")

    c.showPage()
    c.save()
    
    # 5. Upload to Cloud & Update DB
    pdf_payload = buffer.getvalue()
    buffer.close()
    
    storage_path = f"{user_id}/certificates/{skill.lower().replace(' ', '_')}_{level}.pdf"
    
    try:
        bucket_name = _resolve_storage_bucket(supabase)
        supabase.storage.from_(bucket_name).upload(
            path=storage_path,
            file=pdf_payload,
            file_options={"content-type": "application/pdf", "upsert": "true"}
        )

        pdf_url = _build_download_url(supabase, bucket_name, storage_path)
        
        # Update record with the final asset URL
        supabase.table("certificates").update({"pdf_url": pdf_url}).eq("id", cert["id"]).execute()
        
        return {"id": cert["id"], "pdf_url": pdf_url, "verify_code": verify_code}
        
    except Exception as e:
        logger.error(f"Certificate Cloud Storage Error: {e}")
        raise RuntimeError("Certificate generation succeeded but cloud persistence failed.")